### PR TITLE
Fixed spelling of Lua

### PR DESCRIPTION
**Pull request by theOdysseyEffect**
It's not an acronym. It's Portuguese for moon :+1:

### CODE REVIEW

**Comment by muddmaker** [comment]
LGTM!

**Comment by josefnpat** [comment]
+1

**Comment by VideahGams** [comment]
:+1: You don't call it PYTHON

**Comment by Rinnegatamante** [comment]
Nice to see so many haters that don't have nothing better to do that comment a pull request for a miswriting error with trolling messages :D

**Comment by VideahGams** [comment]
Eh? It's not a troll, the Lua devs genuinely don't want you calling it LUA :v

**Comment by Rinnegatamante** [comment]
You came here to comment this pull for whateverr reason? Cause you think i need someone to tell me that it's wrote Lua instead of LUA?

theOdysseyEffect already told whatever is needed to be said so don't came here to comment just to pretend to be acclaimed like a god, autistic boy.

**Comment by VideahGams** [comment]
Because I was passing by and decided to chime in?

Also, I saw the autistic part dickhead, no need to cover your tracks.

**Comment by Rinnegatamante** [comment]
Nothing to hide, i only made my post much clever. I hate when children act thinking they're god and can do whatever they want. This is not a flood forum, this is a developing repository. Grow up idiot.

**Comment by VideahGams** [comment]
`Nothing to hide, i only made my post much clever.`
Editing out insults doesn't make you less of a dickhead, dickhead.

`I hate when children act thinking they're god and can do whatever they want.`
I also hate when narcissistic twats like you think you're above people.

`This is not a flood forum, this is a developing repository. Grow up idiot.`
Coming from the guy who's response to people chiming in on a PR is to flip out and call them autistic.

But whatever, do as you wish I guess.

**Pull request merged**
